"""first migration

Revision ID: a964a3676479
Revises: 
Create Date: 2021-11-03 22:53:42.466928

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a964a3676479'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(length=200), nullable=False),
                    sa.Column('last_name', sa.VARCHAR(length=200), server_default=sa.text('NULL'),
                              nullable=True),
                    sa.Column('username', sa.VARCHAR(length=200), server_default=sa.text('NULL'),
                              nullable=True),
                    sa.PrimaryKeyConstraint('telegram_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
